group = 'org.scopemvc'
version = projectVersion + System.getProperty('suffix', '-SNAPSHOT')

apply plugin: 'java-library'
apply plugin: 'idea'
apply plugin: 'maven-publish'

  sourceCompatibility = JavaVersion.VERSION_1_8
  targetCompatibility = JavaVersion.VERSION_1_8

sourceSets {
  main {
    java.srcDirs = ['src']
    resources {
      srcDirs = ['src']
      exclude '**/*.java'
    }
  }

  test {
    java.srcDirs = ['src.test']
    resources {
      srcDirs = ['src.test']
      exclude '**/*.java'
    }
  }
}

dependencies {
  implementation 'commons-logging:commons-logging:1.0.4'
  compileOnly 'javax.servlet:servlet-api:2.5' // provided
  compileOnly 'javax.servlet.jsp:jsp-api:2.1' // provided

  testImplementation 'junit:junit:3.8.1'
  testImplementation files('lib/jfcunit.jar')
  testImplementation 'javax.servlet:servlet-api:2.5'
}

repositories {
  maven {
    name = 'public'
    url MAVEN_REPO
  }
}

test {
  useJUnit()

  //testoppsettet setter disse, mens rammeverket støtter ikke endringer av dette i runtime
  // se bruk av Locale.setDefault(Locale.UK)
  systemProperty('user.language', 'en')
  systemProperty('user.timezone', 'GMT')
  systemProperty('user.region', 'GB')
//  systemProperty('user.country', 'GB')
//  systemProperty('user.country.format', 'GB')
}

task sourceJar(type: Jar) {
  from sourceSets.main.allJava
  classifier 'sources'
}

publishing {
  publications {
    mavenJava(MavenPublication) {
      from components.java
      artifact sourceJar
    }
  }
}


jar.manifest {
    attributes([
            'Specification-Title'   : project.name,
            'Specification-Vendor'  : 'Statens kartverk',
            'Specification-Version' : (gradle.startParameter.projectProperties.get('projectVersion') ?: projectVersion).replace('-SNAPSHOT', ''),

            //misc build info
            'Build-By'              : System.getProperty('user.name'),
            'Build-Machine'         : java.net.InetAddress.localHost.hostName,
            'Build-Repo'            : MAVEN_REPO,
            'Build-Gradle'          : gradle.gradleVersion,
            'Build-JDK'             : System.getProperty("java.version"),

            'Implementation-Title'  : "${project.name} bygget for ${(version == null || version.contains('-SNAPSHOT') || version.contains('-build')) ? 'TEST' : 'Produksjon'}",
            'Implementation-Vendor' : 'Statens kartverk',
            'Implementation-Version': project.version,
    ])
}

