# Default: log INFO to System.out and a file (no Append)
log4j.rootCategory=INFO, stdout, file


#log4j.category.org.scopemvc.controller.basic.BasicController=DEBUG
#log4j.category.samples.servlet.xml.validation.ValidationController=DEBUG
#log4j.category.test.util.convertor.TestDateStringConvertors=DEBUG
#log4j.category.org.scopemvc.view=DEBUG

# stdout appender includes caller's file name and line number
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
#log4j.appender.stdout.layout.ConversionPattern=%5p [%t] %4r %m%n
log4j.appender.stdout.layout.ConversionPattern=[%-5p %-25c{3} %-4L] %m%n

# daily rolling file, 1000kb max, 5 backups
log4j.appender.roll=org.apache.log4j.DailyRollingFileAppender
log4j.appender.roll.File=scope.log
log4j.appender.roll.layout=org.apache.log4j.PatternLayout
#log4j.appender.roll.layout.ConversionPattern=%d [%t] %-5p %c{3} - %m%n

# file, no Append
log4j.appender.file=org.apache.log4j.FileAppender
log4j.appender.file.File=scope.log
log4j.appender.file.layout=org.apache.log4j.PatternLayout
log4j.appender.file.layout.ConversionPattern=%5p [%t] %4r (%F:%L) - %m%n
log4j.appender.file.Append=false

